vim.opt.number = true
vim.opt.relativenumber = true
vim.opt.autoindent = true
vim.opt.tabstop = 2
vim.opt.softtabstop = 2
vim.opt.shiftwidth = 2
vim.opt.mouse = "a"
vim.opt.clipboard = "unnamedplus"
vim.opt.ignorecase = true
vim.opt.smartcase = true
vim.opt.incsearch = true
vim.opt.splitright = true
vim.opt.splitbelow = true
vim.opt.list = true
vim.opt.undofile = false
vim.opt.scrolloff = 10
vim.opt.listchars = {
	tab = "» ",
	trail = "·",
	nbsp = "␣",
}
vim.opt.confirm = true
vim.opt.scrolloff = 10
vim.opt.shadafile = "NONE"
vim.opt.background = "dark"
vim.opt.updatetime = 100
vim.opt.hlsearch = true
vim.g.editorconfig = true
